// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	User string `json:"user"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
